### PR TITLE
install dev dependencies from testShinyExamples

### PR DESCRIPTION
**Pull request by cpsievert**

### CODE REVIEW

**Comment by jcheng5** [comment]
Hmmm, interesting, it might actually be pretty dangerous to use the dockerfile if you forget to wipe the cache between Shiny releases.

**Comment by cpsievert** [comment]
Ohh, right, maybe this isn't such a good idea :/

**Comment by wch** [comment]
An alternative is to put a script that does all the `install_github()` stuff in the top level of the repo, and then just source that script.

In the Dockerfiles, the script is in /srv/shiny-server/ or /shiny-examples.

**Comment by wch** [comment]
My reservation with this approach is that it doesn't document which app needs which package, so we'll probably end up accumulating cruft over time.

**Pull request closed without merging**
